### ISSUE TITLE
Rubocop yaml

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#1]
There are currently two rubocop configuration yaml files in the project root:
`.rubocop.yml` and `.rubocop_todo.yml`

Is this intentional? Can this be reduced to a single configuration file?

**Comment by Askir** [comment]
@chrisma
Had a lot of offenses in the basic generated project so I ran --auto-gen-config, which is suggested in their wiki. I'll either have to adjust configuration or fix these some time, but at the start it really didn't help me to see 100 errors that couldn't be autofixed.

If you have a code base with an overwhelming amount of offenses, it can be a good idea to use rubocop --auto-gen-config and add an inherit_from: .rubocop_todo.yml in your .rubocop.yml. The generated file .rubocop_todo.yml contains configuration to disable cops that currently detect an offense in the code by excluding the offending files, or disabling the cop altogether once a file count limit has been reached.

**Comment by chrisma** [comment]
Thanks for the info!
