### ISSUE TITLE
Puppet-scripts pushed automatically to git

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#100]
**Beschreibung**
As a user I want generated puppet scripts to be automatically pushed into a git repository, so I don't have to do it manually everytime.

(Jedes mal wenn ein neues Puppet-Script erstellt wird, soll dieses direkt in ein Git-Repo gepushed werden, in dem derzeit bereits alle solchen Scripte gesammelt werden. Da wir derzeit noch keinen Zugang zu diesem Repo haben, soll diese Funktionalität anhand von einem Dummy-Repo demonstriert werden, mit der Möglichkeit nachträglich das Repo in das gepushed wird einfach zu verändern.)

**Akzeptanzkriterien**
- [ ] After a script has been created it is automatically pushed into a git repo
- [ ] The repository being pushed to can be changed easily
 - [ ] Es kann ein SSH key für das Repo hinterlegt werden, damit kein Username und Password für das Git-Repo erforderlich sind

**Priorität**
High

**Aufwandsschätzung**

**Comment by skydivin4ng3l** [comment]
could imagine that the upload process could be started by the creation of the VM cause this may also create the puppet file depending on #99

**Comment by mewitte** [comment]
PR #346

**Comment by arne-z** [comment]
We have tested this on dev with a private repo and it works perfectly.
