### ISSUE TITLE
manage users of vms

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#114]
Depends on #99 

**Beschreibung**
As a wimi I need to be able to edit the users of the vms that I have, so I can manage who gets to use it. For this I want to  be able to see who is currently a user with sudo-rights and who is a user without sudo-rights.
I want to find an edit button on the page that lets me change the users. When I press the save button I want the rights of the users to change.
When I finish editing, I want the puppet-script of the vm to change accordingly.

**Akzeptanzkriterien**
tbd

**Priorität**

**Aufwandsschätzung**

**Comment by BjoernDaase** [comment]
Works!
