### ISSUE TITLE
notification - role has changed

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#116]
**Beschreibung**
As a user, I want to receive a notification if an admin changes my role, so that I become aware of it.
I want a notification to be displayed on my notification-page (#63).
The notification should say "Your role has changed from XXX to XXX on dd.mm.yy".

**Akzeptanzkriterien**
- [ ] Whenever an admin changes a role, the affected user receives a notification on their page saying so.
- [ ] The notification says "Your role has changed from XXX to XXX on dd.mm.yy".

**Priorität**

**Aufwandsschätzung**

**Comment by BjoernDaase** [comment]
Can be closed here because it will be completed with #240.
