### ISSUE TITLE
Integrate GitHub into Slack

### ISSUE THREAD

**Issue by marcfreiheit** [hpi-swt2/vm-portal#120]
**Story**
As a Developer
I would like to have an integration of GitHub in Slack
In order to reference issues directly in Slack and discuss in threads about it.

**Acceptance Criteria**
- [ ] Every channel can decide on its own if they want to opt-in to GitHub features
- [ ] When typing an issue number, Slack provides information the issue by posting a message

**Comment by Kenneth-Schroeder** [comment]
rejected
