### ISSUE TITLE
Is documentation a requirement of the customer?

### ISSUE THREAD

**Issue by MkuuWaUjinga** [hpi-swt2/vm-portal#143]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**
[//]: # (What this issue is about)
We have to clarify, whether extensive, conceptual or technical, documentation of the software is required by the customer.

**Comment by phSch08** [comment]
Nö
