### ISSUE TITLE
Create a template for Contributing.md

### ISSUE THREAD

**Issue by MkuuWaUjinga** [hpi-swt2/vm-portal#144]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

[//]: # (What this issue is about)
We want to write a guide on how to (hypothetically) contribute to our repository. This guide should cover development practices, our work flow (feature branches, when are PR created ...) and other important stuff that comes to our mind.

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by Kenneth-Schroeder** [comment]
rejected
