### ISSUE TITLE
Successful login/logout messages green

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#146]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a user, I want to have the messages I get when I log in or out successfully displayed in green, so that I am not confused why a successful action is displayed in red.

**Acceptance Criteria:**

- [x] Successful-login-message is green
- [x] Successful-logout-message is green
 

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by skydivin4ng3l** [comment]
login green no problem, but logout can be tricky cause the red message is shown cause we are no longer authenticated after login out which is correctly notifying in red. maybe the routing is suboptimal after logout

**Comment by isabel-amon** [comment]
can we make it a neutral color? Maybe grey? Or do you have an idea for better routing?

**Comment by skydivin4ng3l** [comment]
I have an idea now, it is more complex for me alone so it may take a while. The red is coming from the before action i have to find the magic route which handles the session destruction and have to skip this before action for this route. Refactoring the flash messages on the way

**Comment by skydivin4ng3l** [comment]
this is the PR for this story https://github.com/hpi-swt2/vm-portal/pull/189
