### ISSUE TITLE
Archive VMs

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#149]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an employee I want to be able to request the archiving of VMs to not fill up the fast storage of the system. The archive process looks as follows:
- The user clicks a button on the detail page of an active VM to archive it
- All people assigned to this VM will get a notification that their VM will be archived 
- VM will be shut down
- Admin gets a notification that this VM should be archived
- Admin starts the archiving manually which includes
    - Remove IP, Mac, DNS (manually)
    - Migrate storage (manually)
- Admin confirms the archiving with a button
- The VM will be moved automatically in vSphere to “Archived VMs”

**Acceptance Criteria:**
- [x] The VM overview is split in two parts: The upper parts holds an overview of the non-archived VMs, the lower part lists the archived one
- [x] The part of the tables which lists the archived VMs have a gray background
![screenshot from 2019-01-04 13-35-31](https://user-images.githubusercontent.com/24682367/50688452-d848e100-1025-11e9-9fdf-d3b36a632ed5.png)
- [x] Non-archived VMs have a button on their details page which can be used to archive VMs. It is called “Archive”
![screenshot from 2019-01-04 13-38-58](https://user-images.githubusercontent.com/24682367/50688604-7341bb00-1026-11e9-9e6c-d395f126bbaa.png)
- [x] When clicking the “Archive” button all people assigned to this VM will get a notification that their VM will be archived
- [x] When clicking the “Archive” button the VM will be shut down
- [x] When clicking the “Archive” button the admin gets a notification that this VM should be archived
- [x] The admin has a single page which lists all the requests of filings/revivings (following a table layout)
- [x] On that page each VM for archiving has a button “Confirm archiving” 
![screenshot from 2019-01-04 13-44-33](https://user-images.githubusercontent.com/24682367/50689087-8b1a3e80-1028-11e9-8d30-56fc6598dfe2.png)
- [x] When clicking the “Confirm archiving” button the VM will be moved automatically in vSphere to “Archived VMs”
- [x] When clicking the “Confirm archiving” button the VM will be marked as “archived” (and so on moved in the VMs list)
- [x] When clicking the “Confirm archiving” button all its stated users will be informed via Slack
- [x] The new created filings/revivings page follow the design standard

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BraunTom** [comment]
Instead of a single page which lists all the requests of pending archivations, we can keep the requests in the vms list and give them another background color.

**Comment by BjoernDaase** [comment]
Looks good to me!
