### ISSUE TITLE
Revive VMs

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#150]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an employee I want to revive my archived VMs to make them runnable again. It’s the reverse process to the archive process. Depends on #149 (The reverse process).

**Acceptance Criteria:**

- [x] Archived VMs have a button on their details page which can be used to revive VMs. It is called “Revive”
- [x] When clicking the “Revive” button the VM will be listed as a reviving on the filings/revivings page
- [x] When clicking the “Revive” button the admin gets a notification that this VM should be revived
- [x] On that page each VM for reviving has a button “Confirm reviving” 
- [x] When clicking the “Confirm reviving” button the VM will be moved automatically moved out of vSpheres “Archvierte VMs”
- [x] When clicking the “Confirm reviving” button the VM will be marked as “non-archived” (and so on moved in the VMs list)
- [x] When clicking the “Confirm reviving” button the VM will be started again
- [x] When clicking the “Confirm reviving” button all its stated users will be informed via Slack

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BraunTom** [comment]
we should make displaying revive vm/archive vm dependent from the current state of the vm

**Comment by BjoernDaase** [comment]
Reminder (for the VM archiving, @MrModder asked me to place it here): Please move the shutdown action from the "Archive VM" click to the "Confirm Archiving" click.

**Comment by MrModder** [comment]
> Reminder (for the VM archiving, @MrModder asked me to place it here): Please move the shutdown action from the "Archive VM" click to the "Confirm Archiving" click.

This is now a part of the new vSphere API and has already been moved into the correct method

**Comment by BjoernDaase** [comment]
Looks good to me!
