### ISSUE TITLE
restriction for users without root rights

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#158]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a user I want to only be able to start or stop vms if I have root rights to them (#74), so that only people with the right rights can send start and stop requests to a vm.

**Acceptance Criteria:**

- [ ] Story #74 is only available when a user hast root-rights on the vm.

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by isabel-amon** [comment]
you should be able to find out who has root rights, maybe look at #99. When a VM is requested, normal users and users with sudo rights are assigned.

**Comment by mlichtblau** [comment]
@lassesteffen well as @isabel-amon said we actually do, because we don't have a direct association between users and vms we have to associate them via the request that belongs to a vm. And for the association between requests and users we do have a mapping table and each association has the attribute wether the user has sudo rights or not.

**Comment by mlichtblau** [comment]
@janwestphal306 I agree. We were not sure how to ensure that the real VMs in the VSphere are always in Sync with the new model. Now there is an Vsphere API Wrapper which should implement an `sudo_users` method, that always returns the sudo users of the machine as defined by the puppet scripts. #238 is working on importing the puppet scripts to get the sudo rights.

**Comment by mlichtblau** [comment]
We can implement it now by using the sudo users from the request or wait for #238 and implement it then.
Sorry if this sounds confusing.

**Comment by lassesteffen** [comment]
My PR is ready, could need a review and is relying on the requests. Would be cool if we could get it through soon, before it is completely outdated again.

**Comment by NiklasKoehnecke** [comment]
The sudo users from the requests will be outdated once the users are changed since the requests will not be changed but rather taken as they were created. However, #238 will probably still take a while since it depents on #100 and #237
