### ISSUE TITLE
creating projects

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#163]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an employee I want to be able to create new projects in our tool to represent projects in real life. For this I want a separate page where I can set a name for the project and text field that I can put the purpose of the project. Also I want to be able to pick a responsible person (there needs to be at least one). The default-responsible person should be the one creating the new project. There should be a submit-button in order to create the project.

When the submit button is clicked, I want to be redirected to the all-projects page.

**Acceptance Criteria:**

- [x] A page exists that allows creation of projects
- [x] A field for name of the project, description and responsible person exist
- [x] If name and description are not given, there are error messages and submitting does not work
- [x] At least one responsible person must be given for the button "create" to be clickable
- [x] The default responsible person is the person creating the project
- [x] clicking submit leads to the all-projects page #164 

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by lassesteffen** [comment]
@isabel-amon  Can users also create projects or only employees and admins?

**Comment by lassesteffen** [comment]
@isabel-amon is it also okey if the button is clickable but errors are shown when clicking the submit button without name or description?

**Comment by lassesteffen** [comment]
This is way easier than just blocking the button, so would be cool if this is possible

**Comment by isabel-amon** [comment]
@lassesteffen only employees and admins can create projects, the error messages are okay, I will change it in the story. Can you please change the field for responsible people to the same style like the vm request?

**Comment by lassesteffen** [comment]
- [ ] change styling of responsible people field (same as vm request select field)
