### ISSUE TITLE
all projects-page

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#164]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a user, I want a page for projects similar to the all-users page, so I can get an overview over all existing projects. 
I want to be redirected to this page when clicking a button in the header reading "projects".
On this page I want to see a list of all project names and responsible people and I want to be able to click on them in order to get to the page of the project (#166). On the right of the list I want a button saying "create new project" taking me to the create-project page (#163).

**Acceptance Criteria:**

- [ ] A page exists that shows all projects and responsible people
- [ ] Clicking a name leads me to the page of the project #166 
- [ ] There is a button on the page to create a new project #163 

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by skydivin4ng3l** [comment]
blocked by #163
