### ISSUE TITLE
Duplicate VM name results in an error

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#190]
**Summary**

[//]: # (Please provide a details description about the issue you are facing.)

There's a ruby error if I want to create a new VM with an already existing name

**Steps to Reproduce**

[//]: # (Please provide the steps to reproduce the defect. Try to be as specific as possible in order to avoid ambigious testing.)

1. open /vms/new
2. If the vm name already exists, pressing the "create vm"-Button results in an error
![screenshot from 2019-01-04 14-20-56](https://user-images.githubusercontent.com/24682367/50689963-fca7bc00-102b-11e9-9f1d-7773bf6ca483.png)

**Comment by BjoernDaase** [comment]
Seems to be fixed!
