### ISSUE TITLE
Creating a VM with 256,999GB RAM fails

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#192]
**Summary**

[//]: # (Please provide a details description about the issue you are facing.)

When creating a VM with the maximum specified amount of RAM (257GB - 1MB), the creation of the VM fails. 

**Annex**

[//]: # (Please provide screenshots or screencasts if applicable.)

This screenshot tells the user the maximum allowed RAM Size, if he inputs too much in the request form. But when using a allowed amount of RAM, the creation fails.

![image](https://user-images.githubusercontent.com/4164150/49951068-5fa8a600-fef9-11e8-8c04-d4775327c18d.png)

**Comment by BjoernDaase** [comment]
Looks good to me!
