### ISSUE TITLE
Scrolling in numeric fields on vm request creation

### ISSUE THREAD

**Issue by MaximilianKoenig** [hpi-swt2/vm-portal#201]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**
When entering a numeric value, i.e. for the number of CPU cores, it is possible to scroll up/down in order to increase/decrease this value. This behavior can be observed if, and only if, the mouse is exactly over the input field. Having the mouse anywhere else, scrolling works fine.  
Now a user might scroll down in order to scroll down on the page without realising he just modified the entered value.
How to deal with that?

[//]: # (What this issue is about)

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by arne-z** [comment]
Thank you @MaximilianKoenig for the Issue, the PO team is looking into this. Our current opinion is that we would prefer if the fields did not react to scrolling, but this is still in internal discussion. Do you think it would be an easy task changing the way these fields react, or is it something more time-consuming?

**Comment by BjoernDaase** [comment]
I will close it as it didn't come up as a real problem for someone until now.
We will reopen it if that's the case!
