### ISSUE TITLE
hart-dev login failing with Safari

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [hpi-swt2/vm-portal#217]
**Summary**

When trying to log in to the hart-dev website with Safari Browser, an ActionController::InvalidAuthenticityToken Exception is raised.
<img width="771" alt="screenshot 2018-12-22 at 18 14 07" src="https://user-images.githubusercontent.com/20558123/50376965-7e9fea00-0615-11e9-9edc-8082e01d1914.png">

**Comment by BjoernDaase** [comment]
Related to #304 so will be closed here!
