### ISSUE TITLE
Import and Update Puppet scripts

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#238]
Prerequisite #237 

[//]: # (Lines starting with [//]: are considered comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**
As a User
I want the VMs that were created outside of HART to be accessible to me
in order to use the tool with VMs created in the past.

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

**Acceptance Criteria:**

- [x] All the puppet scripts in the puppet repo are read to find out which users should have access to which VMs.
- [x] The git repo containing puppet scripts is either periodically checked for changes, which are then imported or a live version is used, whichever is better from a development/architecture perspective.
   - Research the correct method of staying up to date with the git version and handling concurrent pushes. 
- [x] The current user access rights in the system should match the Puppet scripts in the repository.
- [ ] Changes to user access in the hart system are immediately saved into the repo.
- [x] Git Repo should remain the single point of truth for user access rights at all times.

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by mewitte** [comment]
Tasks:

[ ] Pull current version of repo
[ ] Parse puppet scripts in readable format
[ ] Check existing VMs for updates and edit them
[ ] Check for new VMs

**Comment by BjoernDaase** [comment]
Works and can be closed!
