### ISSUE TITLE
Add notifications to various events

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#240]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a user of HART I want to receive notifications for various events in order to be notified when my action is required, or an event happens that I care about.  
 

**Acceptance Criteria:**

The following is a list of events, and who they should notify, you can find a PDF with BPMN-diagrams attached at the bottom if you want to know more about the processes behind those notifications.
- [x] New request created -> Admins

- [x] Request accepted or rejected -> Requesting user
- [x] Request accepted -> All users that will have rights on this specific VM

- [x] Archiving of VM requested -> All users with access to the VM and the admins (see page 6 of PDF) (The first text line has to be changed to
"The VM will soon be archived and for that it will then be shut down.
If you still need this VM you can stop the archiving of this VM within three days."
- [x] Archiving of VM requested -> Admins
- [x] VM was archived -> All users that will have rights on this specific VM

- [x] Reviving of VM requested -> Admins after X days
- [x] VM was revived from archive -> All users that will have rights on this specific VM

- [x] The role of a user is changed -> The affected user ("Your role has changed from X to Y on dd.mm.yy" + Link to personal profile page)

- [x] Create a new project -> The project responsables ("The project <ProjectName> with you as the responsable has been created" + Link to the projects page)

Some of the above may already have notifications, please communicate with the other teams to check that all of the above are using notifications and doing so in a consistent fashion.

[Processes.pdf](https://github.com/hpi-swt2/vm-portal/files/2749257/Processes.pdf)

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BjoernDaase** [comment]
Looks good to me and worked in demo perfectly today!
