### ISSUE TITLE
Refactoring VM-/Server-/Host-Lists

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#245]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a user
I want to have a better, more intuitive design and layout for the vm/server/host-list-pages
in order to interact better with HART

**Acceptance Criteria:**

- [ ] Refactoring of the layout based on the Mock-Up

Mock-Ups: https://www.figma.com/file/UKvJrtb4zNf9gRr9Gpej5EVO/Mock-Ups?node-id=0%3A1

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by MkuuWaUjinga** [comment]
Will be completed together with #174
