### ISSUE TITLE
all-users page only visible for admin

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#249]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an admin, I want to be the only one to see the all-users page of the tool. Only I want to have the "users" button in the header.
When I click the name of a person only I can see their profile-page.

**Acceptance Criteria:**

- [ ] Only admins have the "Users" button in the header. 
- [ ] Only admins can see the all-users page
- [ ] Admins can click the user names and get to their personal profiles

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by janwestphal306** [comment]
Tasks:
- [ ] Restrict User Button in Header
- [ ] Restrict all users page to admin
- [ ] Restrict own User profile (only me and admins can see my profile)
