### ISSUE TITLE
Request Page refactoring

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#259]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

As an Employee or Admin,
I want the request page to be easy to use
in order to create VMs more quickly.

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

**Acceptance Criteria:**

- [ ] Group entries according to Mockup (follows later)
  - Groups:
    - Name, Description, Responsibilities etc.
    - Hardware (with the selector for template at the top)
    - Specials (Port forward etc.)
    - Comment
 - [ ] A new field for "Responsible User" for each VM request should allow entering Users (like the sudo field etc.)
 - [ ] Responsible Users should be saved with the VM.
 - [ ] Required Fields should be marked with a *
 - [ ] The field for Port and Application name should only be displayed if the user first selects the checkbox "Do you need Port Forwarding?"

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by arne-z** [comment]
@MrModder should be talked to about the Responsible users and where these should be saved.

**Comment by BjoernDaase** [comment]
Looks absolutely gorgeous and so it can be closed!
