### ISSUE TITLE
Init.pp User edits

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#260]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an Admin
I want to have users added to the Init.pp automatically
in order to not have to manually paste every user into the User file.

**Acceptance Criteria:**

- [ ] when new users are added to the User Table the Init.pp is updated

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BjoernDaase** [comment]
Works and looks good!
