### ISSUE TITLE
filter and search all-users page

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#262]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an admin, I want to be able to filter and search the all-users page, to find what I'm looking for faster.
For this I need a search-box that lets me search the names of users as well as a filter for the different roles.

**Acceptance Criteria:**

- [x] There is a search box with which I can search for the name of a user
- [x] There is an option for filtering users by roles

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BjoernDaase** [comment]
Works for now. But we should consider taking the sam search mechanism as on the other sides (VMs, Requests).
