### ISSUE TITLE
Auflistung der VMs/Server

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#27]
Ich als Nutzer möchte eine Auflistung aller existierender Server/VMs sehen um einen grundlegenden Überblick über die Serverstruktur zu bekommen.

- [x] Es gibt eine Seite auf der eine vollständige Liste der VMs bzw. Server sichtbar sind.

Priorität: hoch

**Comment by MkuuWaUjinga** [comment]
_Teilaufgaben:_
- [ ] Die relevanten Daten von vSpehre sind in einem dementsprechenden Modell gespeichert
- [ ] Es exisitiert eine Bootstrap-View für die Server/VM-Liste
