### ISSUE TITLE
Detailseite für Server/VMs

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#28]
Ich als Nutzer möchte zu jedem Server/VM die von vSphere zur Verfügung gestellten Informationen sehen können um einen detaillierten Einblick in das System zu erhalten.

- [x] Die Übersichtsseite verfügt über eine Möglichkeit zu einer Detailansicht einer einzelnen Ressource weiterzuleiten.
- [x] In der Detailansicht sind alle wichtigen Daten über die Ressource zu sehen, insbesondere Hardware-Specs, Auslastung und Logins

Priorität: Mittel

**Comment by MkuuWaUjinga** [comment]
_Teilaufgaben:_
- [ ] Die relevanten Daten von vSpehre sind in einem dementsprechendes Modell gespeichert
- [ ] Es exisitiert eine Bootstrap-View für die Detailseite
