### ISSUE TITLE
General Tasks

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [hpi-swt2/vm-portal#292]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

[//]: # (What this issue is about)
Ask all the Teams about any important remaining Linter-Issues.
Ask teams to respond more quickly on Slack. (enable notifications)
Ask for refactoring.

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by Kenneth-Schroeder** [comment]
Todo: remove DB folder from linting.

**Comment by BjoernDaase** [comment]
I will close this because we will not have SMs anymore.

Please reopen if we have a team structure with SMs again!
