### ISSUE TITLE
Uncertainties architects 

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [hpi-swt2/vm-portal#293]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

[//]: # (What this issue is about)
Check what issues remain for the architects (e.g. second-last bullet point from the 17.01.)

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by BjoernDaase** [comment]
I will close this because we will not have SMs anymore.

Please reopen if we have a team structure with SMs again!
