### ISSUE TITLE
No Manage button, even for admins

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#295]
**Summary**

The `Manage` buttons on the VM detail pages completely disappeared. Even as an admin I can't see them any more at any VM.  
I'm pretty sure that was introduced with https://github.com/hpi-swt2/vm-portal/commit/2fdb9ac46459098cb88f3e3f8bd501ed33e055ca (or is at least related).
 
[//]: # (Please provide a details description about the issue you are facing.)
**Steps to Reproduce**

[//]: # (Please provide the steps to reproduce the defect. Try to be as specific as possible in order to avoid ambigious testing.)

1. Sign in as an admin
1. Visit e.g. https://hart-dev.epic-hpi.de/vms/I-want-this

**Actual Results**

There is no `Manage` button.

**Expected Results**

There is a `Manage` button.

**Annex**

![image](https://user-images.githubusercontent.com/24682367/51694821-e9bc5200-2001-11e9-8acd-9fecfa038927.png)

**Comment by BraunTom** [comment]
I already fixed that admins cannot see the management menu

**Comment by BjoernDaase** [comment]
Seems to be fixed!
