### ISSUE TITLE
Admin can't accept requests

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#296]
**Summary**

As an admin I can't accept request I created, see the image below.

**Steps to Reproduce**

[//]: # (Please provide the steps to reproduce the defect. Try to be as specific as possible in order to avoid ambigious testing.)

1. Sign in as an admin@admin.de
1. Create a valid request
1. Open that request and press "Accept & Continue"

**Actual Results**

You get that pop-up: "You can not change the status of your own requests."

**Expected Results**

The request process would continue. 

**Annex**

![image](https://user-images.githubusercontent.com/24682367/51696243-49682c80-2005-11e9-9548-8764f2873a98.png)

**Comment by lassesteffen** [comment]
@isabel-amon this is already done in #253 should work on dev
