### ISSUE TITLE
/vms doesn't show a users vm (including dashboard)

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#299]
**Summary**

when logged as a user, the /vms page doesn't only show my VMs. It should.
Also, the dashboard shouls mirror the vm-page, please take care of that.

**Comment by lassesteffen** [comment]
Might be related to #326

**Comment by lassesteffen** [comment]
@isabel-amon can you confirm that this is solved?

**Comment by isabel-amon** [comment]
yes, sorry. thanks!
