### ISSUE TITLE
hosts only visible for admins

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#301]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

As an admin, only I need to see the "Hosts" page, as well as the button in the header.

**Acceptance Criteria:**

- [ ] The button "hosts" is only visible to admins
- [ ] The page /hosts is only available to admins

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by skydivin4ng3l** [comment]
should be working, do not understand why tests fail

**Comment by lassesteffen** [comment]
@isabel-amon should be the hosts/specificHostName also be limited to admins?
