### ISSUE TITLE
delete old logins and drop test-users

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#306]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

As a user, now that oAuth works, I no longer need the test logins. If they still appear in the "users" list, I am very confused. 

**Acceptance Criteria:**

- [ ] Only real users are shown in the users list
- [ ] Login with the old test logins doesn't work anymore

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by skydivin4ng3l** [comment]
Auf dev ist jetzt, keine seed mehr mit Userdaten. Sinnvoll wäre einmal die Datenbank zu dropen auf DEV und wo es sinnvoll ist, durch das seeden sollten auf jedenfall keine Testuser mehr rein kommen.

**Comment by skydivin4ng3l** [comment]
Habe Christoph mal gebeten, bei nächster Gelegenheit die DB zu droppen auf den Servern. @isabel-amon reicht das für die Erfüllung der Story?

**Comment by isabel-amon** [comment]
wenn dann keine user@user.de etc erscheinen, schon.

**Comment by skydivin4ng3l** [comment]
@BjoernDaase can you make a note here as soon as the DB is dropped?

**Comment by BjoernDaase** [comment]
Of course. Please tell when I should drop it.

**Comment by BjoernDaase** [comment]
I will not drop Dev, I don't see a reason for that.
But Master is dropped completely so there are no more test users.
