### ISSUE TITLE
Shutdown Guest OS is broken

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#308]
**Summary**

[//]: # (Please provide a details description about the issue you are facing.)

Some of the VM power actions fail. See Screenshot.

![image](https://user-images.githubusercontent.com/4164150/51740556-a5c65d00-2094-11e9-9bdb-348f66ff82ec.png)

Please also include a error handling for power options, so that you will never see a ruby error page.

**Comment by BjoernDaase** [comment]
With #333 being fixed this one can be closed as well.
