### ISSUE TITLE
VM List: Reinclude missing power buttons

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#317]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

[//]: # (What this issue is about)

Please check, where the VM Power Buttons got lost in the VM List.. And reinclude them again.

(Maybe it's an user role related issue..)

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by dey4ss** [comment]
resolved by #302
