### ISSUE TITLE
Confirmation prompt before archiving and confirming archiving

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#322]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a User
I want to have a confirmation prompt show up when archiving a VM
in order to not accidentally click on the button.

**Acceptance Criteria:**

- [ ] The buttons "Archive" and "Confirm Archiving" should each have a confirmation prompt.
   - Both buttons should ask "Are you sure you want to archive this VM?"

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BjoernDaase** [comment]
Works and looks great!
