### ISSUE TITLE
Dashboard cleanup

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#323]
[//]: # (Lines starting with [//]: are considered comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a User
I want to have only important information and my own VMs on my dashboard
in order to have a better experience with the product.

**Acceptance Criteria:**

- [ ] Dashboard shows the users own **active** VMs and **to be archived** VMs 
- [ ] To be archived VMs have a red note with "To be archived"
- [ ] No other VMs are shown on the dashboard, neither other users VMs nor Archived VMs
- [ ] Hosts and/or Servers are not included in the dashboard
- [ ] Notifications are shown on the right of the VMs just like they are now
- [ ] Non-functional buttons (like the delete button) should be removed.
- [ ] Instead of the details button linking to the VM's page the name should link to the VMs page (like it does on the VM list)
- [ ] The VM's status should be visible (again, you can do this just like the VMs page)

If possible it would be great if the Dashboard looks a bit cleaner and more like the VM page, but this is not a functional requirement.

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by janwestphal306** [comment]
Should the dashboard show the same information of a vm as the vms index page?

**Comment by janwestphal306** [comment]
And should an admin be allowed to revive/archive VM that will be archieved?

**Comment by arne-z** [comment]
@janwestphal306 The minimum we need is name and status, but if it is trivially achievable to display the same thing as on the VM index page that would be very nice. 
Being able to confirm archiving from this page would indeed be nice, but again with the time constraints we have it is not needed, and having the feature ready sooner would be preferred.
