### ISSUE TITLE
Users with sudo rights don't get stored with a VM request

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#326]
**Summary**

Users with sudo rights don't get stored with a VM request. Normal users do.

**Steps to Reproduce**

1. Create a new request, assign one user a the users with sudo rights and another at the normal users
1. Have a look at the open request, both users still exist
1. Accept the request and visit the request details page

**Actual Results**

Users with sudo rights is empty.

**Expected Results**

Users with sudo rights should contain the given user

**Annex**

**Comment by MrModder** [comment]
Might be connected to #320

**Comment by BjoernDaase** [comment]
Looks good to me!
