### ISSUE TITLE
HPI-account login

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#33]
**Beschreibung**
As a user I want to be able to login to our tool with my HPI account, so that I don't have to create a new one. When I log in the first time I also want to recieve a UID (starting with 4000).

**Akzeptanzkriterien**
- [ ] When credentials are entered the user is logged in.
- [ ] The user has a unique UID

**Priorität:**
High
**Aufwandsschätzung**
5

**Comment by jakobmache** [comment]
When we log in with OpenID Connect, it redirects to the OpenID Connect page, where the user enters his credentials and confirms the login. If there are no external users any more, do we still need the login form? @marcfreiheit @isabel-amon
