### ISSUE TITLE
Move API information to environment

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#332]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

The API information that is currently hardcoded into both app/api/vmapi and app/api/vsphere/connection should instead be imported from an environment. 

When you merge this change, please make sure to notify everyone to update their environment file.

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by MrModder** [comment]
I would actually recommend removing the old API entirely
As far as I know it is no longer used at all and therefore only dead code.

**Comment by BjoernDaase** [comment]
Looks good to me!
