### ISSUE TITLE
Limit CPU cores to maximum available CPU cores during request

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#333]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an Admin or Employee
I want to be unable to create a VM with more CPU cores than available
in order to not create a VM which will error when starting up.

**Acceptance Criteria:**

- [ ] Limit the CPU cores in the request to the highest CPU cores available from our hosts.

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BjoernDaase** [comment]
@MrModder This should be fixed now (also for RAM and HDD) . But the error output seems not correct to me (see attached image)
![screenshot from 2019-02-09 11-01-20](https://user-images.githubusercontent.com/24682367/52519338-2753e880-2c5a-11e9-9898-bb8a1ea52fae.png)

**Comment by BjoernDaase** [comment]
Fixed in https://github.com/hpi-swt2/vm-portal/commit/abad503f40ace5d89f1958b69792edbb049f1040 and can be closed.
