### ISSUE TITLE
Show IP Address and DNS on VM Detail page

### ISSUE THREAD

**Issue by schmidtflo** [hpi-swt2/vm-portal#348]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

Please show the IP address and DNS entry for an VM on the VMs detail page.

**Comment by BjoernDaase** [comment]
Looks good to me!
