### ISSUE TITLE
SSH Key in init.pp

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#354]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a User
I want to have my ssh key in the init.pp file
in order to be able to connect to VMs via ssh

**Acceptance Criteria:**

- [ ] When a user sets or edits his SSH key, the init.pp is updated with the new SSH key

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by BjoernDaase** [comment]
Is fixed!
