### ISSUE TITLE
Angemeldeter Nutzer

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#38]
**Beschreibung**
Ich als angemeldeter Nutzer möchte nach der Anmeldung meinen Namen in der Kopfleiste sehen, damit ich auf einen Blick sehen kann überprüfen kann, wer der gerade angemeldete Nutzer ist.
**Akzeptanzkriterien**
Eine Möglichkeit, den aktuell angemeldeten Nutzer  in der Kopfleiste zu sehen, existiert.
**Priorität:**
Mittel
**Aufwandsschätzung**
1

**Comment by mlichtblau** [comment]
Wie soll die Anzeige denn aussehen? Stellst du dir so eine Übersichtsseite vor wo du dein ganzes Profil anschauen kannst oder möchtest du nur zB die Menü Leiste anpassen, sodass statt Login irgendwas anderes da steht?
