### ISSUE TITLE
make settings configurable via settings page 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#399]
**User Story**
As an administrator, I want a new menu item (left to the notification icon). The menu item should be the font awesome cog. This menu item should have a submenu "settings", which links to the settings page.    
The settings page should have the design of the VM request page and should be able to configure the settings for git, vsphere, archiving time, and mailer. 

**Acceptance Criteria:**

- [x] create a model to store settings in the database
- [x] create a menu item with cog icon
- [x] submenu item "settings" links to settings page
- [x] make settings for git, vsphere... configurable
- [x] remove all corresponding environment variables

**Comment by BjoernDaase** [comment]
@MrModder We still need descriptions for the categories on the settings page (to completely match the new request page). Do you specific ideas for the content of them @krichly?
