### ISSUE TITLE
Einheitlicher Design-Standard

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#4]
Ich als Nutzer möchte einen ansprechende, einheitliche Oberfläche haben, damit die Anwendung einen einheitlichen Eindruck macht.
- [x] Es gibt eine klar dokumentierte Richtlinie für das Design der Seite.

Schätzung: 13

**Comment by hkohlsaat** [comment]
@arne-z wirf bitte einen Blick auf diese ["Design Standart" Wiki-Seite](https://github.com/hpi-swt2/vm-portal/wiki/Design-Standart).
