### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#40]
**Beschreibung**
Ich als Nutzer möchte mich nach erfolgreichem Login wieder abmelden können, damit ich eine Sitzung beenden kann. Dafür möchte ich einen Knopf in der Kopfleiste finden, der mir ersichtlich macht, dass ich mich darüber ausloggen kann. Nach dem Logout möchte ich auf die Login-Seite geleitet werden, damit ich oder jemand anders sich erneut einloggen kann.
**Akzeptanzkriterien**
Ein Button existiert, der als Logout-Button erkennbar ist.
Sein Klicken führt zum Logout
Nach dem Ausloggen landet man auf der Login Seite, damit wieder die Möglichkeit besteht, sich einzuloggen.
**Priorität:**
Mittel
**Aufwandsschätzung**
1

**Comment by mlichtblau** [comment]
Route wird durch devise gem zu Verfügung gestellt, nur ein Button muss noch in den Header eingefügt werden.
Dürfen wir selbst das Header Partial hinzufügen?
Warten auf #3 bzw Antwort von @hpi-swt2/az-18 ?
