### ISSUE TITLE
configurable vsphere root folder 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#400]
**User Story**

As an administrator, I want to set a vsphere root folder on the settings page. The hart system should create the folder in vsphere center and only manage the vms inside this folder.  

**Acceptance Criteria:**

- [ ] Root folder can be specified on settings page
- [ ] In the vsphere space on the settings page should be the possibility to set a hart root folder.
- [ ] The corresponding folder is created in the vsphere center 
- [ ] Only the vms inside this hart root folder are managed by hart. All other vms are ignored.

**Comment by MrModder** [comment]
Should VMs that are not inside the selected root folder be displayed in HARTs VM Overview page?
Or should they not exist as HART is concerned?
Latter would be easier to implement

**Comment by BjoernDaase** [comment]
> Should VMs that are not inside the selected root folder be displayed in HARTs VM Overview page?
> Or should they not exist as HART is concerned?
> Latter would be easier to implement

VMs outside of the root folder do not exist for HART!
