### ISSUE TITLE
refactoring of dashboard

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#406]
**User Story**
refactoring of dashboard 

![bildschirmfoto 2019-02-18 um 14 04 14](https://user-images.githubusercontent.com/5772525/52955626-6e925580-338d-11e9-8c5a-0b126f0cbf16.png)

**Comment by BraunTom** [comment]
Not more than 10 per widget

**Comment by BraunTom** [comment]
No Buttons for Notificaions and delete when read
Delete stays
