### ISSUE TITLE
Make request settings configurable via settings page 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#409]
**Description**

make parameters for vm requests configurable on the settings page (e.g., `MAX_CPU_CORES`, see `app/models/request.rb`)

min + max values for cores, ram, and storage

**Related Issues**

- #399

**Comment by chrisma** [comment]
Add sensible defaults for these settings in the `seeds.rb` so that I can use the system out of the box without having to configure variables.
