### ISSUE TITLE
uid 4000 in init.pp on hart-bot/epic-user-config-dev 

### ISSUE THREAD

**Issue by mat156** [hpi-swt2/vm-portal#422]
**Summary**

[//]: # (Please provide a details description about the issue you are facing.)
Die init.pp der dev-Umgebung enthält bei allen Usern die uid 4000. Das ist bei der init.pp vom Master nicht der Fall. Da ich die generierten Dateien gerade auf dev teste, gibt es Fehlermeldungen im puppetrun.

**Comment by BjoernDaase** [comment]
@mat156 Die einzige Lösung, die ich dafür sehe, wäre die komplette Datenbank auf dev zu droppen (Grundproblem: Es gab Nutzer, die schon vor der Gitanbindung existierten). Das Problem tritt aber auf jeden Fall nicht wieder auf.
@MrModder @BraunTom Seht ihr eine bessere Möglichkeit?

**Comment by MrModder** [comment]
@mat156 Die interne Architektur ist hier sehr merkwürdig. Die User in HART bekommen neben der ID die ihnen automatisch von Rails zugewiesen wird noch eine extra ID für die Puppetscripts.
Ich kann mir nicht genau erklären warum das der Fall ist...
Gibt es noch irgendwelche speziellen Anforderungen an die User-IDs in den puppetscripts, außer dass diese >= 4000 sein müssen?
Wenn nicht können wir das so umstellen, dass einfach die Rails-ID + 3999 als User-ID genommen wird. das würde auch die interne Architektur aufräumen.

**Comment by mat156** [comment]
@MrModder prinzipiell kann das so gemacht werden. Wichtig ist nur zu bedenken, dass wir ja irgendwann noch den Import vom Original init.pp der Live Umgebung machen wollen. Also nicht nur Rails-ID und raufaddieren, sondern auch schauen, dass die uid auch wirklich unique ist.
Aufräumen ist immer gut.

**Comment by MrModder** [comment]
Ah, okay,
Dann wäre es wahrscheinlich wirklich keine gute Idee diesen Code zu entfernen…
Wir können wie @BjoernDaase schon gemeint hat natürlich die DB droppen.
Oder wir schreiben ein kleines Script, dass auf HART einfach allen usern mit fehlender oder uneindeutiger user_id eine neue zuordnet

**Comment by MrModder** [comment]
Wir müssen in Zukunft auch mehr darauf achten in Zukunft passende Migrations zu schreiben, sodass keine notwendigen Felder leer bleiben

**Comment by mat156** [comment]
dann lasst uns einmal die DB droppen. Was passiert nach dem Reset mit den VM's die auf dem Cluster laufen? Werden die wieder eingelesen oder müssen die via HART Request neu erstellt werden. Dann würde ich nach dem Reset die Basisfestplatten sichern und dann die VM's erneut erstellen lassen.

**Comment by MrModder** [comment]
Die VMs werden eh immer direkt aus vSphere ausgelesen.
Es werden nur HART-spezifische Informationen verloren gehen. Also die Description, Project, Responsible, etc.
Das ist relativ harmlos, da die vSphere-API von uns für genau solche Fälle entwickelt wurde. Die API nimmt nie an, dass die VM in HART bekannt ist.
Die VMs werden genauso wie vorher angezeigt. Minus die Zusatzinfos.

**Comment by mat156** [comment]
Dann weg damit und ich teste morgen weiter.

**Comment by MrModder** [comment]
So, DB ist resettet, init.pp sieht jetzt wieder gut aus.
