### ISSUE TITLE
puppet scripte nicht kompilierbar

### ISSUE THREAD

**Issue by mat156** [hpi-swt2/vm-portal#423]
Wir müssen noch einmal an die Puppet Skripte ran. Unter Name wird eine Wrapperklasse für puppet definiert, die bestimmten Konventionen entsprechen muss (vor allem die Art der Sondernzeichen ist begrenzt auf den Unterstrich)
In der ersten Zeile von Name steht der Name der VM in einfachen Anführungsstrichen. In der anschliessenden node und class Definitionen dürfen außer Unterstrichen keine anderen Sonderzeichen stehen (auch keine Leerzeichen).

Name
IST:
```
node 'vm-foreman-hartdev'{

    if defined( node_vm-foreman-hartdev) {
                class { node_vm-foreman-hartdev: }
    }
}
```

SOLL:
```
node 'vm-foreman-hartdev'{

    if defined( node_vm_foreman_hartdev) {
                class { node_vm_foreman_hartdev: }
    }
}

```
korrspondierend in Node
IST:
```
class node_vm-foreman-hartdev {
        $admins = ["Matthias.Herzog"]
        $users = ["Matthias.Herzog"]

        realize(Accounts::Virtual[$admins], Accounts::Sudoroot[$admins])
        realize(Accounts::Virtual[$users])
}
```

SOLL:
```
class node_vm_foreman_hartdev {
        $admins = ["Matthias.Herzog"]
        $users = ["Matthias.Herzog"]

        realize(Accounts::Virtual[$admins], Accounts::Sudoroot[$admins])
        realize(Accounts::Virtual[$users])
}
```

**Comment by MrModder** [comment]
Hm, das wird etwas knifflig zu lösen sein...
Beim erstellen eines VM-requests wird automatisch jeder whitespace durch Bindestriche ersezt. Weshalb viele der VMs bereits Bindestriche beinhalten.
Wir müssen dann irgendwie enforcen, dass VMS in HART dieselben Namen-Beschränkungen haben wie die Klassen in Puppet. Oder wir müssen uns eine Variante überlegen, wie wir die Namen der VMs so in die node-scripts übernehmen, dass sie keine Sonderzeichen beinhalten, aber trotzdem eindeutig sind

**Comment by mat156** [comment]
Nicht zu kompliziert denken: der VM Name kann genau so bleiben. Nur bei der Erstellung der Puppet Skripte dürfen keine Striche mehr drin sein in der class und node Beschreibung. Irgendwo werden die Daten doch eh genommen und umgewandelt, an dieser Stelle zusätzlich noch auf die Unterstriche achten.

**Comment by MrModder** [comment]
Auf jeden Fall geht das, ich vermute aber mal, dass die Puppet klassennamen eindeutig sein müssen.
Das ist problematisch, sollte es 2 VMs geben, die zwar in vSphere unterschiedlich heißen, aber in den selben Puppet Klassennamen übersetzt werden.
z.B.: my_VM und my-VM würden dann beide in node_my_VM übersetzt werden.

**Comment by mat156** [comment]
#424 sollte das lösen, so dass man sich hier nur auf das Übersetzen konzentrieren muss.

**Comment by MrModder** [comment]
Ich habe dazu noch einen Vorschlag ein #424 eingebracht

**Comment by BjoernDaase** [comment]
Done with #424 in #441
