### ISSUE TITLE
VM request page: validations for vm name 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#424]
**User Story**

As an administrator, I want that names of vms are unique. Also, I want that "Umlaute" are forbidden and not automatically converted (e.g., ü -> u).     

**Acceptance Criteria:**
- [ ]  Add validation to ensure that vm names are unique
- [ ] Refactor regular expression to forbid "Umlaute" 
- [ ] Update error message: the message should state that "-" is allowed

**Comment by MrModder** [comment]
As discussed in #423 in the puppet scripts class names, no special characters (like "-") are allowed, only "_" is.
Therefore it might make sense to enforce the same naming conventions here to eliminate the possibility of duplicate names when creating the puppet scripts.
I would like to include this change as acceptance criteria here if you don't mind.

Proposed updated criteria:
- [ ] Add validation to ensure the vm names are unique (including open requests)
- [ ] No longer allow any kind of special character (except for "_")
- [ ] Update error message: the message should state that "_" is allowed
- [ ] The name is no longer changed automatically, but rather the request is prohibited from being saved

**Comment by mat156** [comment]
This will collide with my running infrastructure and their DNS names. At the moment there are 270+ VM's with "yymmdd_vm-some-name" scheme. At VM creation I would like to limit names to [a-z1-9] + "-" as the only special char allowed.
At puppet script creation these "-" shall be converted to "_"

**Comment by MrModder** [comment]
Ok, but we should still disallow any other special characters apart from "-" to assure a safe way to convert to puppet scripts without creating name interferences.

 So, new acceptance criteria:
- [ ] Add validation to ensure the vm names are unique (including open requests)
- [ ] No longer allow any kind of special character (except for "-")
- [ ] Update error message: the message should state that "-" is allowed
- [ ] The name is no longer changed automatically, but rather the request is prohibited from being saved
