### ISSUE TITLE
vSphere vm name 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#425]
**User Story**
As an administrator, I want that the vm names in the vSphere Center include the creation date in order to have this information (e.g., how old a vm is) also in vSphere available.

naming convention: `<yyyy><mm><dd>_vm-<vmname>`, e.g. `20190301_vm-myvm`
`<vmname>` should be lowercase

**Acceptance Criteria:**

- [ ] the system is able to create and access vms with the specified naming convention

**Comment by MrModder** [comment]
Should those vm-names also be displayed that way in HART?
Or should the prefix be removed there? VM names are currently read plainly out of vSphere without a translation step

**Comment by chrisma** [comment]
> Should those vm-names also be displayed that way in HART?
> Should those vm-names also be displayed that way in HART?
No, just the vm name should be displayed

> Or should the prefix be removed there?
Yes

> VM names are currently read plainly out of vSphere without a translation step
This should be changed accordingly
