### ISSUE TITLE
Refactor buttons on editing request page  

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#430]
**Description**

The section on the bottom of the page should be refactored corresponding to the screenshot. 
![img_3325](https://user-images.githubusercontent.com/5772525/53485376-59e94800-3a86-11e9-9713-056d4e149dd4.JPG)

**Comment by BjoernDaase** [comment]
So the "Request notification" should be removed within this issue?

**Comment by krichly** [comment]
This issue should only restructure the following section.
<img width="1552" alt="bildschirmfoto 2019-02-27 um 16 10 05" src="https://user-images.githubusercontent.com/5772525/53500233-3fc16100-3aaa-11e9-9866-567618bd52b8.png">

**Comment by BjoernDaase** [comment]
Sorry, I ment "Reject information"

**Comment by BjoernDaase** [comment]
@krichly So we have two comments then, right?
But the new comment (which is filled out by the admin) should then be treated as the old "Reject information"?

**Comment by chrisma** [comment]
> @krichly So we have two comments then, right?
Yes, there is a comment on the VM request, which a requester can fill out to communicate with the admin, e.g. "please quick".
there is also a comment, that the admin can give when accepting / rejecting a VM. In the case of rejection, this comment by the admin is displyed to the user as the reason for rejection. Int he case of acceptance, the comment is displayed as a comment on the VM show page as a comment for the VM.

This behavior should be described to the admin on the VM request acceptance / rejection page, e.g. using the above text.

**Comment by BjoernDaase** [comment]
> > @krichly So we have two comments then, right?
> 
> Yes, there is a comment on the VM request, which a requester can fill out to communicate with the admin, e.g. "please quick".
> there is also a comment, that the admin can give when accepting / rejecting a VM. In the case of rejection, this comment by the admin is displyed to the user as the reason for rejection. Int he case of acceptance, the comment is displayed as a comment on the VM show page as a comment for the VM.
> 
> This behavior should be described to the admin on the VM request acceptance / rejection page, e.g. using the above text.

Thanks for clearing this up!
