### ISSUE TITLE
Edit Ip and dns

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#431]
**Description**

For an administrator, it should be possible to edit the dns and ip for existing vms.

**Comment by BjoernDaase** [comment]
@MrModder As you already said today, we have to talk about whether we can reuse the config page. This would imply, that the editing of users is possible on the config page.

**Comment by MrModder** [comment]
@krichly @BjoernDaase I strongly encourage using a single edit page for the vms, after creation to configure IP and DNS, and also to edit the VM afterwards.
This would better conform to the REST principles, provide better reusability, and even give greater configuration control after creating the VM, if need be.
We would only have to change the redirect url depending on whether someone was redirected there from creation, or just edited the VM
