### ISSUE TITLE
Refactor login for development environment 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#437]
**Description**

I would prefer if we could refactor the login for the development environment. Since the rest of the system requires that each user has a valid OpenID account, I would propose the following steps:

- [x] remove all code, which is used for the user/password authentication of devise   
- [ ] all developers configure the HPI OpenID provider for their local setup
- [x] if run in `development` mode we disable the checks for the user page, so that each user can switch between the different roles

**Comment by krichly** [comment]
We will stay with Max Mustermann.

**Comment by BjoernDaase** [comment]
Closed via https://github.com/hpi-swt2/vm-portal/pull/439.
