### ISSUE TITLE
Make mac address copy link great again 

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#446]
https://hart-dev.epic-hpi.de/vms/configs/show

**Comment by BjoernDaase** [comment]
`00:50:56:ac:c5:dd` is what I copied! 
What exactly is the problem?

**Comment by BjoernDaase** [comment]
Seems like a subtask of https://github.com/hpi-swt2/vm-portal/issues/452. So can we close it?

**Comment by chrisma** [comment]
> Seems like a subtask of #452. So can we close it?

Yup, thanks for pointing that out.
