### ISSUE TITLE
Replace dynamic generation of puppet scripts with templating

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#447]
Puppet scripts are currently being dynamically generated: `https://github.com/hpi-swt2/vm-portal/blob/dev/lib/puppetscript.rb`

This means that code is fairly hard to read and maintain.

Instead, consider using templates for puppet scripts, i.e. `puppet.erb.pp` that is then filled with variables just like RoR views or RoR mailers are.

**Comment by MrModder** [comment]
How would we then handle reading puppet scripts back in?
Is there a way for .erb to reverse the generation process, so match a file and write into some specified variables?

**Comment by chrisma** [comment]
> Is there a way for .erb to reverse the generation process, so match a file and write into some specified variables?

Not that I am aware of. That is not a usual use case for templating. I'm not sure if investigating the support of puppet file parsers for ruby is worth the effort. Most likely, parsing the scripts with regexes will do.
