### ISSUE TITLE
created VMs in wrong vsphere network

### ISSUE THREAD

**Issue by mat156** [hpi-swt2/vm-portal#449]
Beim automatischen Erstellen von VMs wird die NIC der Maschine im Netzwerk 'VM Network' eingerichtet. Da dieses Netzwerk nicht existiert, wird es automatisch von vSphere erstellt. Es gibt aber ein Standard Netzwerk, in welchem alle VMs erstellt werden sollen.
Die vSphere API sollte eine Liste zurückliefern und das oberste Element ausgewählt werden. Ansonsten funktioniert das automatische Deployment und der pxeboot nicht.

**Comment by BjoernDaase** [comment]
Just for my personal understanding: NIC = Network Interface Card?

**Comment by mat156** [comment]
> Just for my personal understanding: NIC = Network Interface Card?

correct

**Comment by mat156** [comment]
Die Frage ist, was aktuell bei der Erstellung der VM passiert. Mich würde interessieren, wie der API call aussieht und ob man dort das zu verwendende Netzwerk mitschicken kann.

**Comment by BjoernDaase** [comment]
> Die Frage ist, was aktuell bei der Erstellung der VM passiert. Mich würde interessieren, wie der API call aussieht und ob man dort das zu verwendende Netzwerk mitschicken kann.

Ich habe leider viel zu wenig Ahnung von der vSphere API. @MrModder weißt du da mehr?
