### ISSUE TITLE
Refactoring VMs config page

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#452]
- [x] Relocating operating system 
- [x] Update text elements (see picture) 

Related Issues: #449, #446 

<img width="1015" alt="bildschirmfoto 2019-03-07 um 12 53 22" src="https://user-images.githubusercontent.com/5772525/53957016-8ed84900-40dd-11e9-9012-c802f28a7630.png">

**Comment by BjoernDaase** [comment]
Why would you remove the comment? If the user requested a OS, that is not in the OS list (e.g. a Windows Server), he should write the OS he wants to be installed in the comment. So I think the comment field is absolutely necessary.

**Comment by BjoernDaase** [comment]
@BraunTom Copying could be easily done with JS, right?

**Comment by krichly** [comment]
Good question: I didn't think about this problem. So I would propose to display the comment field under the operating system field, but only if the comment field is not empty.
