### ISSUE TITLE
VM Index page should load even when not connected to the HPI network

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swt2/vm-portal#47]
Currently the vm index page doesn't load when connected to a network other than the HPI network, but throws a 500 internal server error. 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/22854083/48613935-55909780-e98d-11e8-9943-a96793b138c8.png">

It would be helpful to get a response with a descriptive error message.

Probably every other page that tries to connect to the vms is affected, so a general approach would be helpful.

Maybe @hpi-swt2/bd-18 or @hpi-swt2/fs-18 can take on this issue?

**Comment by mlichtblau** [comment]
Hm ok wie du meinst ^^
Aber ist die Frage ernst gemeint?

**Comment by fyndalf** [comment]
@mlichtblau I saw that you did some changes for this in #62 - do you know when that MR will be ready?

**Comment by mlichtblau** [comment]
Hey @fyndalf I just merged the PR. I don't think the next PR is going to be a problem as the changes to the `VmController` are quite small.
