### ISSUE TITLE
Remove hart_form_builder from assets

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#476]
Helper class is in assets folder: `app/assets/helpers/hart_form_builder.rb`.
This means that Rails asset pipeline will attempt to compile and serve the file.

**Comment by BjoernDaase** [comment]
Where should it be instead?

**Comment by BjoernDaase** [comment]
Btw. it was placed here, because we followed the instructions from https://coderwall.com/p/-biuug/custom-form-builders-in-rails.

**Comment by chrisma** [comment]
See https://github.com/hpi-swt2/vm-portal/pull/486
