### ISSUE TITLE
Deletion of projects

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#488]
> Why do we not allow to destroy projects? Is there never a point we might have to many of them and they have to be cleaned up?

Most likely it should be possible to delete projects.

**Comment by mat156** [comment]
should be able to delete

**Comment by BjoernDaase** [comment]
@chrisma Do we need additional checks when deleting a project? E.g., that this may not result in a VM loosing its project?

**Comment by chrisma** [comment]
> @chrisma Do we need additional checks when deleting a project? E.g., that this may not result in a VM loosing its project?

I guess we should warn if there are still VMs connected to a project, but if a user really wants to delete that project, they should be able to. I don't think the deletion of a project should cascade down to VMs and delete them too.
@mat156 Agreed?

**Comment by BjoernDaase** [comment]
@chrisma Alright. And who is allowed to delete projects? Every employee may create them but it could have bad outcome, if every employee would also be allowed to delete projects from others. And what is about the responsible users? May the delete projects?

**Comment by chrisma** [comment]
> who is allowed to delete projects?

Everyone who is also able to edit the project.
