### ISSUE TITLE
Final styling adjustments for index pages

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#494]
[//]: # (Please use this template for arbitrary tasks which aren't bugs or user stories. This issue type can be used for internal and development f)
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**Description**

With #475, which nicely cleaned up a lot of code, we got a few, in my view, styling issues introduced:
- [x] The table rows on the dashboard (and also the VM index page) have different hights 
![image](https://user-images.githubusercontent.com/24682367/54716933-40a05c80-4b57-11e9-83f7-107e8717e830.png)
- [x] The buttons for the actions for VMs aren't aligned in one way (either left or right in their column) and have different paddings
![image](https://user-images.githubusercontent.com/24682367/54717044-8ceb9c80-4b57-11e9-844c-7c1fc607db9b.png)
- [x] The search bars aren't placed in one way anymore
![image](https://user-images.githubusercontent.com/24682367/54717077-a4c32080-4b57-11e9-9517-a5594c860baa.png)

**Related Issues**

- #475

[//]: # (Feel free to add new sections if required. Don't forget to add a priority as a label.)

**Comment by chrisma** [comment]
> The table rows on the dashboard (and also the VM index page) have different heights

https://github.com/hpi-swt2/vm-portal/pull/495/commits/cfa9826ae6309733497b7d618bbf1667b0af8076

> The buttons for the actions for VMs aren't aligned in one way (either left or right in their column) and have different paddings

See changes in `app/views/vms/*_buttons.erb` : https://github.com/hpi-swt2/vm-portal/pull/495/files

> The search bars aren't placed in one way anymore
The search bars in line with the `h1` are by design

**Comment by chrisma** [comment]
Adressed in https://github.com/hpi-swt2/vm-portal/pull/495

**Comment by BjoernDaase** [comment]
> The search bars in line with the h1 are by design
Alright, then is it misplaced on the Users page

**Comment by chrisma** [comment]
> Alright, then it is misplaced on the Users page

Fine 😊 https://github.com/hpi-swt2/vm-portal/pull/495/commits/0ef5c166f2ca4fcef3531f1da7b2fe31512a3cdc

**Comment by BjoernDaase** [comment]
> > Alright, then it is misplaced on the Users page
> 
> Fine  [0ef5c16](https://github.com/hpi-swt2/vm-portal/commit/0ef5c166f2ca4fcef3531f1da7b2fe31512a3cdc)

Perfect 👌
