### ISSUE TITLE
Seite zum Anlegen von VMs

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#5]
**Beschreibung**
Ich als WiMi wünsche mir eine Seite, auf der ich eine VM beim Admin anfragen kann, damit ich eine VM nach meinen persönlichen Wünschen erhalten kann.

**Akzeptanzkriterien**
- [x] Existenz einer spezifischen Website für diesen Zweck
- [x] Mehrere Forms/Felder auf dieser Seite, insbesondere
  - [x] Feld für OS Auswahl
  - [x] Felder für Hardwareressourcen (insbesondere Prozessoren, RAM, Sekundärspeicher)
  - [x] Liste in der verschiedene Software ausgewählt werden kann, die man zur Installation wünscht
  - [x] Freifeld für Kommentare
  - [x] Abschicken-Button

**Priorität:**
Hoch

**Aufwandsschätzung**
5

**Comment by MaxSchneider1337** [comment]
Wir brauchen eine Auswahl von Software, Betriebssysteme etc. Müssen uns nochmal mit dem Kunden absprechen, was hier genau zur Auswahl stehen soll.

**Comment by BjoernDaase** [comment]
Minimal Changes:

mb --> MB
Comments and Software fields bigger

**Comment by skydivin4ng3l** [comment]
Is this the page where the user can specify which users should have which privileges? Cause it does not have it as acceptance criteria. We would need this information about the user privileges for this issue #97 .

**Comment by BjoernDaase** [comment]
Looks good to me!
