### ISSUE TITLE
Issue Templates for Pull Requests and Bug Reports

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swt2/vm-portal#50]
**Beschreibung**

As a developer I want to have Bug Report and Pull Request Templates in order to ensure consistency and simpler issue creation

**Akzeptanzkriterien**

Templates can be used when clicking new issue on Github

**Aufwandsschätzung**

**Comment by BjoernDaase** [comment]
Does anybody already have a template they like? Or specific wishes?

**Comment by marcfreiheit** [comment]
> Does anybody already have a template they like? Or specific wishes?

We will take care of it and create a pull request within the next days. Then you can decide which version you would like to choose.
