### ISSUE TITLE
Master Branch should be protected

### ISSUE THREAD

**Issue by mlichtblau** [hpi-swt2/vm-portal#51]
**Beschreibung**

As a developer I want my master to be protected in order to save it from unwanted changes

**Comment by BjoernDaase** [comment]
I changed the settings so that only pull requests are allowed to change the master branch. By default, the approved reviews counter is set to 1 and I didn't change it.
Du you have further requirements or wishes we should apply? Should we change the reviews level?

**Comment by mlichtblau** [comment]
@BjoernDaase thanks, I think 1 reviewer should be enough for the moment!
