### ISSUE TITLE
Investigate why rendering VMs index is slow

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#512]
* Investigate what part of the VMs index page load is the bottleneck
* Investigate why loading `VMs#index` and `dashboard`, creates multiple of the following queries:
>   VirtualMachineConfig Load (0.2ms)  SELECT  "virtual_machine_configs".* FROM "virtual_machine_configs" WHERE "virtual_machine_configs"."name" = ? LIMIT ?  [["name", "vm-foreman-hartdev"], ["LIMIT", 1]]
  ↳ app/api/v_sphere/virtual_machine.rb:232

* If buttons are to blame, move them to VM#details
* consider creating a separate "archived VMs" page

**Comment by chrisma** [comment]
@mat156 The archived VMs list will eventually be quite large, right? and would most likely not be needed very often?

**Comment by mat156** [comment]
this is correct.

**Comment by chrisma** [comment]
Idea: Don't render VM buttons on the index page, but only on show / detail pages, to cut down on the required API calls
