### ISSUE TITLE
Pfadbezeichnungen sind RESTful

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#58]
**Beschreibung**
Ich als Nutzer wünsche mir eine RESTful entsprechende Benennung der URIs um die Zusammenhänge leichter zu erkennen.

**Akzeptanzkriterien**
- [x] Der Path /vm heißt /vms
- [x] Die aktuell unter /requests liegenden Seiten sollen unter /vms/requests/ liegen
- [x] Das Formular zur Anfrage einer neuen VM ist unter /vms/requests/new erreichbar
- [x] Das Formular zur Erstellung einer neuen VM ist unter /vms/new erreichbar
![swt2_4](https://user-images.githubusercontent.com/24682367/48860005-ec12ed80-edbf-11e8-8c9e-d7e37a2dd082.png)

**Priorität**
hoch

**Aufwandsschätzung**

**Comment by MaxSchneider1337** [comment]
@BjoernDaase 

Are you sure that request/new should map vms/new, because we already got a vm(s)/new side, wich is currently used to create the vm(with or without a corresponding request)? And what should we call  the old vm(s)/new page?

**Comment by BjoernDaase** [comment]
@MaxSchneider1337 I had a look at it today, looks all in all good to me.
One thing that is missing, is that the header, when clicking on 'VMs', directs me to `/vm` and not `/vms`. Could you please make sure that that works properly?

**Comment by MaxSchneider1337** [comment]
- [ ] vm in headed

**Comment by BjoernDaase** [comment]
Looks good to me!
