### ISSUE TITLE
Vorhandene OS in VM-Anfrage zur Verfügung stellen

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#60]
**Beschreibung**
Ich als Nutzer möchte in dem VM-Anfrageformular in der OS-Auswahl die schon vorhanden OS zur Auswahl haben damit die VM auch mit dem gewünschten OS erstellt werden kann. Außerdem möchte ich, dass ich auch mittels "Others" keines dieser OS auswählen kann.

**Akzeptanzkriterien**
- [x] Die Auswahl des OS ist eine Liste, aus der man nur genau einen Eintrag auswählen kann
- [x] Die Einträge dort spiegeln die schon erstellten OS aus #93 wider
- [x] Es soll außerdem eine Others Auswahl geben

**Priorität**
hoch

**Aufwandsschätzung**

**Comment by BjoernDaase** [comment]
Is this already merged into dev?

**Comment by BjoernDaase** [comment]
@MaxSchneider1337 @regnujAx We still have the duplicates in the list (at least in the deployed version). Are you aware of that issue?

**Comment by regnujAx** [comment]
@BjoernDaase 
I can't estimate if this is simple to solve or not but yes, I know it. Maybe it is better to make a new issue so we can't forget it. 
What is your opinion @MaxSchneider1337?

**Comment by BjoernDaase** [comment]
Looks good to me!
