### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#64]
**Beschreibung**
**Als** Nutzer 
**möchte ich** eine Sitemap
**damit ich** eine Übersicht über die webseite bekomme.

EIne [HTML-Sitemap](https://www.sistrix.com/ask-sistrix/sitemaps/are-there-different-kinds-of-sitemaps/#HTML-Sitemap) sollte alle routes auf der Seite darstellen und für nutzer verständlich anzeigen

**Akzeptanzkriterien**

 - [ ] Eine Sitemap kann vom Nutzer eingesehen werden
 - [ ] Die Sitemap verlinkt zu alle anderen Seiten
 - [ ] Ein Link zu Sitemap ist im Footer zu finden

**Priorität**
Niedrig

**Aufwandsschätzung**

**Comment by krichly** [comment]
Not needed!
