### ISSUE TITLE
Name für das VM-Portal

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#67]
**Beschreibung**
**Als** Nutzer
**möchte ich** einen auf der gesamten seite einheitlich verwendeten namen für die Seite haben
**damit ich** die seite wiederfinde und über sie mit anderen nutzern reden kann.

Der Kunde hat den namen Hart 4 bereits abgelehnt. Der name der Seite sollte darauf hindeuten was die funktion der seite ist, und nicht unprofessionell wirken. 

**Akzeptanzkriterien**
 - [ ] Drei Vorschläge für den namen der seite sind an die POs gesendet worden, um ein OK vom Kunden zu bekommen.
 - [ ] Nach OK des Kunden: Alle erwähnungen von “Hart” oder “VM-Portal” auf der seite sind einheitlich durch den namen ersetzt.

**Priorität**
Hoch

**Aufwandsschätzung**
3

**Comment by henleo** [comment]
**Tasks**  
- [ ] Vorschläge sammeln 30min
- [ ] Vorschläge auswählen, Kommunikation mit PO's 30min
- [ ] Namen auf der Seite vereinheitlichen 1h
