### ISSUE TITLE
profile-page

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#77]
**Beschreibung**
As a user, I'd like to see a profile-page, on which I can see all important information about myself. When I click on my name in the header, I want to be redirected there. On the page I find my name, e-mail adress and a possibility to store my ssh key.

**Akzeptanzkriterien**
- [x] Clicking on the name in the header redirects to the profile-page
- [x] E-mail adress is displayed
- [x] Name of user is displayed
- [x] Possible to see if ssh-key was stored or not

**Priorität**
High
**Aufwandsschätzung**

**Comment by lassesteffen** [comment]
@isabel-amon I think it is not necessary that there is a reference for the ssh key in this story. There is a different story for this issue already
