### ISSUE TITLE
ssh-key

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#78]
**Beschreibung**
As a user I need a way to store my ssh-key in the tool. For this I'd like a button on the profile page, which when I click on it displays a field in which I can put my key. Then I need a button to save my key. If I already have a key stored, I want to see a button that allows me to change the key, similar to putting a new one. I'd also like it, if the key is valid, when I click the button. It should not be saved if it is not valid.

**Akzeptanzkriterien**
- [x] Button to store exists, if there was no key stored yet
- [x] If a key is already stored, a button to change and delete should exist
- [x] Clicking of the buttons leads to a field in which changes can be made
- [x] Clicking the delete-button leads to deletion of the key
- [x] If the key entered is invalid, it should not be saved an a message should be displayed

**Priorität**
Medium
**Aufwandsschätzung**

**Comment by skydivin4ng3l** [comment]
- [ ] display ssh key only on own user page
