### ISSUE TITLE
uniform design

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#85]
**Beschreibung**
As a user, I want the tool not only to work, but also to look good. I want all existing pages to have the look defined in the design templates.
**Akzeptanzkriterien**
- [ ] Login-page, personal profile and all-users look like the design template.
- [ ] (All other newly added pages as well)

**Priorität**
High
**Aufwandsschätzung**

**Comment by lassesteffen** [comment]
- request/accept accounts look like the design template
Is this still relevant?`Can this go ìnto another issue?

**Comment by isabel-amon** [comment]
yes, I will take it out
