### ISSUE TITLE
Seite zum Verwalten der zur Verfügung gestellten OS

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#93]
**Beschreibung**
Ich als Admin wünsche mir eine Seite auf der ich die Liste der zur Auswahl stehenden OS bearbeiten kann.

**Akzeptanzkriterien**
- [x] Diese Liste enthält initial folgende Betriebssysteme: CentOS 7, SLES 11 SP3 und Ubuntu 18.04
- [x] Sie ist editierbar, das heißt es lassen sich Betriebssysteme löschen und neue hinzufügen 
- [x] Bei dem "erstellen" eines neuen Betriebssystems lässt sich nur sein Name angeben

**Priorität**
hoch

**Aufwandsschätzung**

**Comment by BjoernDaase** [comment]
Is this already merged?

**Comment by BjoernDaase** [comment]
@MaxSchneider1337 @regnujAx 
Where do I find it? 'hart-dev.epic-hpi.de/operating_systems' returns an error for me.

**Comment by regnujAx** [comment]
@BjoernDaase 
Did you try 'hart-dev.epic-hpi.de/vms/requests/operating_systems'?

**Comment by BjoernDaase** [comment]
Looks good to me!
