### ISSUE TITLE
Port-forwarding für externen Zugriff

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swt2/vm-portal#95]
**Beschreibung**
Ich als Nutzer möchte beim VM-Anfrageformular einen Port sowie einen Namen zur Weiterleitung der VM über den Proxyserver angeben können damit ich auch von außerhalb des HPI-Netzes auf die VM zugreifen kann.

**Akzeptanzkriterien**
- [ ] Ich kann bei dem Anlegen der VM einen Port angeben. Dieser soll aus einem sinnvollen Bereich sein
- [ ] Ich kann bei dem Anlegen der VM einen Namen angeben. Dieser ist der Nam über den ich die VM von außerhalb erreichen kann
- [ ] Die Felder müssen nicht ausgefüllt sein, können also leer gelassen werden und sind dann auch korrekt
- [ ] Der Port muss **nicht** auf Validität/Korrektheit überprüft werden

**Priorität**
niedrig

**Aufwandsschätzung**

**Comment by regnujAx** [comment]
@BjoernDaase Should the port and the name also be listed on the requests index and show page?

**Comment by BjoernDaase** [comment]
Definitely on the details/show page!
We should also try to list it on the overview page, but that depends on the clarity of that page. If we find out that the information in the overview get to much and confusing, we should drop it there.

**Comment by BjoernDaase** [comment]
Looks good to me!
