### ISSUE TITLE
creating puppet scripts

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#97]
**Beschreibung**
As an admin I want to receive a puppet-script after a VM request has been approved, in which I can find important information to my VM, so that I can use it to create accounts. I'd like to see a button that allows me to see the puppet-file in raw text, like the github "raw" button. This button should be found on the detail page for the approved request. 

Beispiel eines Puppet Scripts:
```
class node-vm-username-operatingsystem {
    $admins = ["FirstName.LastName", "FirstName2.LastName2"]  
    $users = ["FirstName3.LastName3." , ... ]  

    realize(Accounts::Virtual[$admins], Accounts::Sudoroot[$admins])  
    realize(Accounts::Virtual[$users])  
}  
All names are based on HPI-Active Directory accounts, 
therefore they can include numbers if there are two or more students with the same names.
```

**Akzeptanzkriterien**
- [ ] After a VM request has been accepted, a button should be visible on the VMs request page, that leads to its puppet file in plain text.

**Priorität**
High

**Aufwandsschätzung**

**Comment by skydivin4ng3l** [comment]
references #100

**Comment by skydivin4ng3l** [comment]
discuss with @hpi-swt2/bd-18 about how users get priviliges in the created VM, accessing User DB for instance

**Comment by skydivin4ng3l** [comment]
discuss with @hpi-swt2/bd-18 possible contents of puppet files

**Comment by skydivin4ng3l** [comment]
startet a discussion with @BjoernDaase about this.
