### ISSUE TITLE
User angeben bei VM-Anfrage

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#99]
**Beschreibung**
Ich als Nutzer möchte beim dem Request einer VM angeben wer außer mir Zugriff auf die VM bekommen soll damit auch andere beteiligte Personen mitarbeiten können.

**Akzeptanzkriterien**
- [x] Es gibt eine Liste in der die schon hinzugefügten Extranutzer stehen
- [x] Dieses ist initial leer
- [x] Es können zusätzliche User anhand ihrer HPI E-Mail Adresse (bzw. dem Teil vor dem @) angegeben werden (mittels einem +-Button) unter der Liste
- [x] Nutzer können durch das Klicken auf das x wieder entfernt werden (via einem x ganz rechts in der Liste)
- [x] Es kann den einzelnen hinzugefügten Nutzern ein Label "Sudo" gegeben werden (via Checkbox, links von dem x zum Entfernen)
- [x] Ein Nutzer mit Sudorechten ist außerdem farblich hinterlegt

**Priorität**
Hoch

**Aufwandsschätzung**

**Comment by skydivin4ng3l** [comment]
related to #97

**Comment by BjoernDaase** [comment]
Looks good to me!
